### ISSUE TITLE
issues loading  two blendshape target animation

### ISSUE THREAD

**Issue by negativecitizen** [ArhasGH/Maya-Live-Link-CSV-Import#1]
Hi,
First of all thank u for all the great plugin .
Testing I've found some issues with the loading of two targets "**mouthRollLower**" and "**mouthRollUpper**" they dont receive any data for some reason. Ive tested on Maya 2018 and  2020. 
besides that,works great.
Thanks 
![Screen Shot 5-12-2021 at 2 26 PM](https://user-images.githubusercontent.com/69877435/118033307-46a4b900-b32e-11eb-960c-8220ee522c80.png)

**Comment by aronamao** [comment]
Hey,
this is happening due to the way it tries to differentiate between joints and blendshapes, back when I wrote the plugin it seemed like no blendshapes use Yaw, Pitch or Roll in the name so I just checked for that. 
I would like to stay away from hardcoding names but I do not use the plugin myself and I therefore don't really know which rules I could apply to figure out the difference between blendshape and joint. 
The easiest way to fix it that I can think of would be to check if there's anything after Yaw/Pitch/Roll, do you know if it's possible that blendshapes end with those?

**Comment by negativecitizen** [comment]
ohh, its that , I understand. I've changed some names  and get that data .Thanks for the info .  i thinks in this case hardcode some names probably isn't that  bad because initially apple arkit did it . Also in my case  and (probably in several cases) the data of  the bone rotation isnt the most important because  the data  of the neck  and  head is yet acquired by another body mocap system , so in my case is redundant to certain point , and also is  nearly eliminated by the use a hmc or helmet in which the phone is attached. Another reason is  because the structure of  riggings  change a lot  ,including names  ,joint orientations,etc (some pipelines use  ctrl curves with fancy names  and some put data directly  in the   joints).Thanks again for reply

**Comment by aronamao** [comment]
I will keep it as is for now and add a disclaimer to the readme, if this is an issue that comes up again I will fix it.
